/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.rafaelbfs.sparsearrays;

import org.junit.jupiter.api.Test;

import java.util.List;

import io.github.rafaelbfs.sparsearrays.ValuedRange;

// import static org.junit.jupiter.api.Assertions.*;

class RangeArrayTest {

    @Test void someLibraryMethodReturnsTrue() {
        var queries = List.of(new ValuedRange(2, 6 ,8),
                new ValuedRange( 3, 5, 7),
                new ValuedRange(1, 8 ,1),
                new ValuedRange(5, 9 , 15));

        var rangeTree = new RangeAvlTree();

        for (var query : queries) {
            rangeTree.insert(query);
        }

        System.out.println(rangeTree);
    }
}
