/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.rafaelbfs.sparsearrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
